### ISSUE TITLE
Undefined <result.strokeOrderSvgUri>

### ISSUE THREAD

**Issue by sarekashi** [mistval/unofficial-jisho-api#13]
First, thank you for making this API project.
Second, when I use your API to print result.strokeOrderSvgUri what I get is Undefined and the trouble is in the animationUri link in the index.js file.
I hope you can update it with a new link, thank you.

**Comment by mistval** [comment]
Hello, could you give me an example of what query(s) return an undefined strokeOrderSvgUri? I noticed that the gif URIs are outdated so I'll fix that, but the SVG URIs seem okay with the queries I tested with.

**Comment by sarekashi** [comment]
ahh sorry, I mean result.strokeOrderGifUri

**Comment by sarekashi** [comment]
I think I have the answer to this, thank you for answer my question

**Comment by mistval** [comment]
Fixed in new version 1.4.2 on NPM. c7f83bbafa
