### ISSUE TITLE
Searching for Kanji with more than one is not found

### ISSUE THREAD

**Issue by TopHatMan** [mistval/unofficial-jisho-api#14]
Ex : 言語 returns false but searching for 言 returns found.

more complex searches break.

**Comment by mistval** [comment]
Jisho.org only has kanji results for single kanji, so it's unsurprising that nothing is found if you search for multiple kanji.

If you want to search for both of those kanji, you'll need to search for them one at a time. If you want to search for the word 言語, you can use the searchForPhrase function instead.
