### ISSUE TITLE
reading of jukugo

### ISSUE THREAD

**Issue by lingolab2** [mistval/unofficial-jisho-api#19]
I'd like get the reading of a jukugo.
The following provides meaning but not the reading. 
How can one achieve this?
```
jisho.scrapeForPhrase('電車').then((data) => {
  console.log(JSON.stringify(data, null, 2));
});
```

**Comment by mistval** [comment]
You can use `searchForPhrase` instead:

```js
jisho.searchForPhrase('電車').then((data) => {
  const reading = data.data[0].japanese[0].reading;
  console.log(reading);
});
```

scrapeForPhrase should only be used for things that searchForPhrase doesn't have.

**Comment by lingolab2** [comment]
works perfectly  thank you. any chance to get at newspaper frequency if available?

**Comment by mistval** [comment]
That is in the kanji search results:

```js
const JishoApi = require('unofficial-jisho-api');
const jisho = new JishoApi();

jisho.searchForKanji('語').then(result => {
  console.log('Newspaper frequency rank: ' + result.newspaperFrequencyRank);
});
```

**Comment by lingolab2** [comment]
this would work only for Kanji and not for compound words (jukugo), right?

**Comment by mistval** [comment]
Yes, I didn't think Jisho.org shows newspaper frequency for anything except single kanji search results. Am I mistaken?

**Comment by lingolab2** [comment]
you’re most likely right. wanted to refresh existing data about jukugo. probably from some other source. i’ll search. thanks
