### ISSUE TITLE
sameSite attribute issue

### ISSUE THREAD

**Issue by DhansAL** [mistval/unofficial-jisho-api#31]
I'm getting this "issue" on the console,
`Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute`
while working with this API.
and because of this, I cant make multiple requests with this API. I tried resolving it on client side but didn't found any promising solution.

**Comment by mistval** [comment]
Hello, to use this module, or the Jisho API in general, in a web browser, you would need to use a proxy to get around cross-origin resource sharing restrictions. This is due to server-side configuration on Jisho.org that we don't control.

**Comment by DhansAL** [comment]
oh if thats the case ill do so, thanks :)
