### ISSUE TITLE
Enable Option for CORS

### ISSUE THREAD

**Issue by Doderich** [mistval/unofficial-jisho-api#48]
It would be a good idea to create a option to add a url of a CORS reverse proxy server infront of the jisho url. That would enable this api to also work on browser-side applications.

**Comment by mistval** [comment]
Hi, you could use the parsing functions discussed in the README under `Parsing HTML strings` to implement something like this.

I don't feel it would be appropriate to add direct CORS proxy support to this library since the Jisho admins may have reasons for leaving CORS disabled.
